---
experiment_name: final_run
target: GDPC1
target_lag: 124
factor_type: [pca]
generate_data: True
hyperparameter_search: True
fit_best_configs: True
train_end: null
end_date: 2013-12-31
regularize: xgb
standardize: True
alpha: 2.0
max_length: 730
window_type: days
fill_method: ffill
level: [3, 4]
keep_sigs: all
t_level:
l1_ratio: 0.0
use_multiplier: True
fit_intercept: True
use_quarter_time: True
use_prev_value: True
basepoint: False
